### ISSUE TITLE
你好，我想问下你这个dict.bin文件是怎么样还原出来的

### ISSUE THREAD

**Issue by smithyj** [TooBug/pinyin#4]
你好，我想问下你这个dict.bin文件是怎么样还原出来的，我是做PHP的，看不大懂你的JS

**Comment by TooBug** [comment]
`dict.bin`的结构很简单，就是把汉字的utf8码和汉字的拼音拼接起来变成二进制写入。

其中汉字的编码是定长的，拼音是不定长的，“汉字+拼音”之后使用换行符`\n`分隔。

生成的详细过程可以参考`tools`目录，有原始的码表和转换代码。

查找时问题的核心就在于如何找到汉字的编码，因为汉字编码是有序写入文件的，所以用二分查找。

核心的代码在`searchfile.js`中，其中的三个参数：

- `offsetFunc`用于将二分查找时的字节位置进行微移，找到`\n`分隔的位置
- `bufferFunc`用于判断当前取到的是不是一个完整有效的buffer
- `assertFunc`用于判断是否找到目标，如果没找到，指示应该往前找还是往后找

整体逻辑大概就是这样，供参考。

另外，hotoo的源库在后来也进行了大幅性能优化，也可以作为参考。

**Comment by smithyj** [comment]
昨天研究了一天，看懂了，3Q
